version: '3.4'

volumes:
  db_volume:

services:
  remixedapi:
    image: remixedapi:latest
    build: ./backend
    ports:
      - "8000:80"
    depends_on:
      - db
    environment: 
      DB_CONNECTION_STRING: "host=db;port=5432;database=recipedb;username=postgres;password=postgres"

  db:
    image: postgres:latest
    environment: 
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "recipedb"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  client:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app