version: "3"

volumes:
local_postgres_data: {}

services: 
  web:
    build: ./back
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./back:/app
      - /app/RemixedRecipe/bin
      - /app/RemixedRecipe/obj
    depends_on: 
      -db
  db:
    image: postgres:13
    environment: :
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volume:
      - local_postgres_data:/var/lib/postgresql/data

  client
    build: ./front
    ports:
      - "4200:4200"
    volumes: 
    - ./front:/app